# Google Cloud Build configuration for Saikum backend deployment
# This file tells Cloud Build how to build and deploy the Next.js backend

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'apps/backend/Dockerfile'
      - '-t'
      - 'us-docker.pkg.dev/$PROJECT_ID/saikum-backend/saikum-backend:$COMMIT_SHA'
      - '-t'
      - 'us-docker.pkg.dev/$PROJECT_ID/saikum-backend/saikum-backend:latest'
      - 'apps/backend'
    id: 'build-image'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-docker.pkg.dev/$PROJECT_ID/saikum-backend/saikum-backend:$COMMIT_SHA'
    id: 'push-image'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'saikum-backend'
      - '--image'
      - 'us-docker.pkg.dev/$PROJECT_ID/saikum-backend/saikum-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
    id: 'deploy-cloud-run'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/saikum-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/saikum-backend:latest'

# Build timeout
timeout: '1200s'

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
