import 'package:hive_flutter/hive_flutter.dart';
import '../../l2_domain/models/workout.dart';
import '../../l2_domain/models/workout_exercise.dart';
import 'boxes.dart';

/// Hive database configuration and initialization
class HiveConfig {
  static bool _initialized = false;

  /// Initialize Hive and register all adapters
  static Future<void> initialize() async {
    if (_initialized) return;

    // Initialize Hive with Flutter
    await Hive.initFlutter();

    // Register type adapters (generated by build_runner)
    Hive.registerAdapter(WorkoutAdapter());
    Hive.registerAdapter(WorkoutExerciseAdapter());

    // Open boxes
    await Hive.openBox<Workout>(HiveBoxes.workouts);

    _initialized = true;
  }

  /// Close all boxes (for cleanup)
  static Future<void> close() async {
    await Hive.close();
    _initialized = false;
  }

  /// Clear all data (for testing/reset)
  static Future<void> clearAll() async {
    final box = Hive.box<Workout>(HiveBoxes.workouts);
    await box.clear();
  }
}
